### ISSUE TITLE
Request for Full Paper Text

### ISSUE THREAD

**Issue by Tokisakix** [LQlq123/FairCRS#1]
Dear Repository Author(s),

Congratulations on having your paper accepted to RecSys '24! I recently came across your repository and found the research incredibly insightful. The work aligns closely with my own research, and I would love to dive deeper into your findings.

As the paper has not yet been made publicly available, I wanted to kindly request if you could share the full paper with me via email. My email address is: xurlin5@mail2.sysu.edu.cn

Once again, congratulations on your achievement, and I look forward to hearing from you!

Best regards,
Tokisakix

**Comment by LQlq123** [comment]
Hello, thank you for your attention! Here is a link to the article: https://dl.acm.org/doi/10.1145/3640457.3688150. Good luck with your research!
